### ISSUE TITLE
Tracking issue for final changes before the Q1 2021 release

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge-frontend#150]
- [x] #149 
- [x] #136 (functionality only, may be without nice-looking UI) + [PR#10](https://github.com/near/rainbow-bridge-client/pull/10) [PR#11](https://github.com/near/rainbow-bridge-client/pull/11)
- [x] Update the list of tokens according to #112 (comment)
- [x] #105 (comment)
- [x] Change on the login screen 'Don’t have a NEAR account? Create one here.' -> 'Need a NEAR account? Create one here.'
- [x] Change the links to the URLs according to #105 (comment) when switching between the networks
- [x] During scheduling the `deployBridgeToken` transaction change the [appropriate amount](https://github.com/near/rainbow-bridge-client/blob/main/packages/nep141-erc20/src/bridged-nep141/deploy.js#L56) for contract storage
- [x] Change everywhere the NEAR-side token names from `DAI^n` to `nDAI`
- [x] Update [the wording for the transfer steps](https://github.com/near/rainbow-bridge-client/pull/8):
  - Approve transfer of 5.1 TST from Ethereum
  - Convert 5.1 TST to nTST
  - Wait for 20 Ethereum confirmations for security
  - Deposit 5.1 nTST on NEAR
  - ------
  - Withdraw 0.1 nDAI from NEAR
  - Convert 0.1 nDAI to DAI
  - Sync withdrawal transaction to Ethereum (up to 24 hours)
  - Deposit 0.1 DAI in Ethereum

**Comment by djsatok** [comment]
Completed
